### ISSUE TITLE
Where is CFPushButton.h

### ISSUE THREAD

**Issue by haps-basset** [caiofrota/cf-arduino-lib-rotary-encoder#2]
The CFRotaryEncoder.h requests  CFPushButton.h which is not combined with the release

**Comment by ItsFlo** [comment]
CFPushButton.h is from another library which you have to download seperately.
https://github.com/caiofrota/cf-arduino-lib-pushbutton

**Comment by caiofrota** [comment]
Thank you for answering @ItsFlo 

https://github.com/caiofrota/cf-arduino-lib-pushbutton
